# Generated by Django 4.2.6 on 2023-10-30 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('unite', models.CharField(max_length=30)),
                ('valeurMin', models.FloatField()),
                ('valeurMax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('datePrise', models.DateTimeField()),
                ('grandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grandeurs.grandeur')),
            ],
        ),
    ]
